#!/usr/bin/env ruby
#
if ARGV[0]
  raise "#{ARGV[0]} ???" unless system("which '#{ARGV[0]}' 2> /dev/null")
  RUBY = "#{ARGV[0]} -W0 -I ./lib"
else
  RUBY = 'ruby -W0 -I ./lib'
end

EXAMPLES = './examples'
LOG = './tmp/error.log'

Dir.entries(EXAMPLES).each do |file|
  file  = File.join EXAMPLES, file
  if File.file?(file)
    unless system("#{RUBY} #{file} 2> #{LOG}") and File.zero?(LOG)
      abort("Error in #{file}.  See #{LOG}.")
    end
  end
end
