#! ruby
require 'test/unit'
require 'such/parts'

module Such
  def self.subclass(name, klass, **kw, &block)
    [name, klass, kw, block]
  end

  module Part
  end

  class Thingy
  end
end

class TestParts < Test::Unit::TestCase
  def test_make
    # No such class "Zingy" for a superclass
    assert_raises(RuntimeError){Such::Parts.make(:Part, :Zingy, :plug_Whatchamacallit)}

    # Plug must be in the form :key_class
    assert_raises(RuntimeError){Such::Parts.make(:Part, :Thingy, :plug)}

    part, thing, kw, block = Such::Parts.make(:Part, :Thingy, :a_Abc, :xyz_Xyz)
    assert_equal :Part, part
    assert_equal :Thingy, thing
    assert_equal Hash, kw.class
    assert_equal Proc, block.class
  end
end
