#! ruby
require 'test/unit'
require 'such/such'

class SomeClass
  def initialize(v)
    @value=v
  end
end

module SomeModule
  def value
    @value
  end
end

class TestSuch < Test::Unit::TestCase
  def test_subclass
    assert_nothing_raised() do
      a_class = Such.subclass(:AClass, SomeClass, include: SomeModule)
      assert_equal Such::AClass, a_class
      this_instance = Such::AClass.new('This Value')
      assert_equal 'This Value', this_instance.value
    end
  end
end
