#! ruby
require 'test/unit'
require 'such/things'

module A
  class X
  end
  class X1 < X
  end
  class X2 < X
  end
  class X3 < X
  end
end

module Gtk
  class Widget
  end
  class A < Widget
  end
  class B < Widget
  end
  class C < Widget
  end
end

module Such
  LIST = []
  def self.subclass(clss)
    raise 'WUT?' unless ['A','B','C'].include?(clss)
    LIST.push(clss)
  end
end

class TestThings < Test::Unit::TestCase
  def test_list
    assert_equal(Such::Things.list(A::X).sort{|a,b| a.name<=>b.name}, [A::X1,A::X2,A::X3])
    assert_equal(Such::Things.list.sort{|a,b| a.name<=>b.name}, [Gtk::A,Gtk::B,Gtk::C])
  end

  def test_gtk_widget
    assert_nothing_raised() do
      Such::Things.gtk_widget
    end
    assert_equal(Such::LIST.sort, ['A','B','C'])
  end
end
