#!/usr/bin/env ruby

if ARGV[0]
  raise "#{ARGV[0]} ???" unless system("which '#{ARGV[0]}' 2> /dev/null")
  RUBY = "#{ARGV[0]} -I ./lib"
else
  RUBY = 'ruby -I ./lib'
end
LOG = './test/errors.log'

def fn(name)
  "./test/tc_#{name}"
end

def tc(name)
  system "#{RUBY} #{fn(name)} > #{LOG}"
end

if tc('version') and
   tc('thing')   and
   tc('such')    and
   tc('things')  and
   tc('part')    and
   tc('parts')
  puts 'All tests passed!'
  File.unlink LOG
else
  abort("There were errors.  See #{LOG}.")
end
