#! ruby
require 'gtk3'
require 'such'
include Such; Things.in Gtk::Widget

gray = Gdk::RGBA::new(0.2, 0.2, 0.2, 1)
bardejov = GdkPixbuf::Pixbuf.new :file => "images/grumpy1.png"
rotunda  = GdkPixbuf::Pixbuf.new :file => "images/grumpy2.png"
mincol   = GdkPixbuf::Pixbuf.new :file => "images/grumpy3.png"

Thing.configure(
  window: {
    override_background_color: [:normal, gray],
    set_title: 'Fixed',
    set_default_size: [300,280],
    set_window_position: :center,
  },
)

window = Window.new(:window, 'destroy'){Gtk.main_quit}
  fixed = Fixed.new window
    Image.new fixed, [pixbuf: bardejov], {into: [:put, 20, 20 ]}
    Image.new fixed, [pixbuf: rotunda],  {into: [:put, 40, 160]}
    Image.new fixed, [pixbuf: mincol],   {into: [:put, 170, 50]}
window.show_all

Gtk.main
