#! ruby
require 'gtk3'
require 'such'
include Such; Things.in Gtk::Widget

Thing.configure(
  window: {
    set_border_width: 10,
    set_title: 'Gtk::FontSelectionDialog',
    set_default_size: [300, 150],
    set_window_position: :center,
  },
  label!: [['The only victory over love is flight.'], {into: [:put,30,90]}],
  button!: [[label: 'Select font'], {into: [:put,100,30]}],
)

def on_clicked(label)
  fdia = Gtk::FontChooserDialog.new :title => 'Select font name', :parent => @window
  response = fdia.run
  label.override_font(fdia.font_desc) if response==Gtk::ResponseType::OK
  fdia.destroy
end

@window = Window.new(:window, 'destroy'){Gtk.main_quit}
fix = Fixed.new(@window)
label = Label.new(fix, :label!)
Button.new(fix, :button!, 'clicked'){on_clicked(label)}

@window.show_all
Gtk.main
