#! ruby
require 'gtk3'
require 'such'
include Such; Things.in Gtk::Widget

Thing.configure(
  window: {set_border_width:2, set_title:'Blushing', set_window_position: :center},
  IMAGE:  [file: 'images/grumpy1.png'],
)

window = Window.new :window, 'destroy' do Gtk.main_quit end
Image.new :IMAGE, window
window.show_all
Gtk.main
