#! ruby
require 'gtk3'
require 'such'
include Such; Things.gtk_widget

AGR = Gtk::AccelGroup.new
GRAY = Gdk::RGBA.new(0.2,0.2,0.2,1)

def stock(id) [stock_id: id, accel_group: AGR] end

def acc(a)
  k,m = Gtk::Accelerator.parse a
  {add_accelerator: ['activate', AGR, k, m, Gtk::AccelFlags::VISIBLE]}
end

Thing.configure(
  window: {
    override_background_color: [:normal, GRAY],
    add_accel_group: AGR,
    set_title: 'Image Menu',
    set_default_size: [300,200],
    set_window_position: :center,
  },

  FILE: ['File'],

  VBOX: [:vertical, 2],

  NEWI: stock(Gtk::Stock::NEW),
  newi: acc('N'),

  OPENM: stock(Gtk::Stock::OPEN),
  openm: acc('O'),

  EXIT: stock(Gtk::Stock::QUIT),
  exit: acc('Q'),
)

window = Window.new(:window, 'destroy'){Gtk.main_quit}
  vbox = Box.new window, :VBOX
    mb = MenuBar.new vbox, {into: [:pack_start,expand:false,fill:false,padding:0]}
      filem = MenuItem.new mb, :FILE
        filemenu = Menu.new filem
          ImageMenuItem.new filemenu, :newi!
          ImageMenuItem.new filemenu, :openm!
          SeparatorMenuItem.new filemenu
          ImageMenuItem.new(filemenu, :exit!, 'activate'){Gtk.main_quit}
window.show_all

Gtk.main
