#! ruby
require 'gtk3'
require 'such'
include Such; Things.in Gtk::Widget

Thing.configure(
  window:  {
    set_title:           'Quit Button',
    set_default_size:    [300,200],
    set_window_position: :center
  },
  window!: [:window, 'destroy'],

  BUTTON:  [label: 'Quit'],
  button:  {set_size_request: [80,35], into: [:put,50,50]},
  button!: [:BUTTON, :button, 'clicked'],
)

window = Window.new :window! do Gtk.main_quit end
fixed  = Fixed.new window
Button.new fixed, :button! do Gtk.main_quit end
window.show_all

Gtk.main
