#! ruby
require 'gtk3'
require 'such'
include Such; Things.in Gtk::Widget

Thing.configure(
  window:
    {set_title:'Center', set_default_size:[300,200], set_window_position: :center, show:nil}
)
Window.new :window, 'destroy' do Gtk.main_quit end
Gtk.main
