#! ruby
require 'gtk3'
require 'such'
include Such; Things.in Gtk::Widget

Thing.configure(
  window: {
    set_border_width: 15,
    set_default_size: [350,300],
    set_window_position: :center,
  },

  grid: {
    set_column_spacing: 5,
    set_row_spacing: 5,
  },

  ALIGN1: [0,0,0,0],
  align1: {
    into: [:attach,0,0,1,1],
  },

  ALIGN2: [0,0,0,0],
  align2: {
    into: [:attach,0,4,1,1],
  },

  TITLE: ['Windows'],

  frame: {
    set_hexpand: true,
    set_vexpand: true,
    into: [:attach,0,1,3,3],
  },

  VBOX: [:vertical, 4],
  vbox: {into:[:attach,3,1,1,1]},

  button: {
    set_size_request: [70,30],
    into: :add,
  },
  act_btn!: [[label: 'Activate'], :button],
  cls_btn!: [[label: 'Close'], :button],
  hlp_btn!: [[label: 'Help'], :button],
)

window = Window.new(:window, 'destroy'){Gtk.main_quit}
grid = Grid.new window, :grid
align1 = Alignment.new grid, :align1!
Label.new align1, :TITLE
Frame.new grid, :frame
vbox = Box.new grid, :vbox!
Button.new(vbox, :act_btn!){puts 'Activate'}
Button.new(vbox, :cls_btn!){puts 'Close'}
align2 = Alignment.new grid, :align2!
Button.new(align2, :hlp_btn!){puts 'Help'}
window.show_all
Gtk.main
